---
driver:
  name: vagrant


provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[amazon-ecs-agent]
    attributes:

  - name: default-ec2
    driver_plugin: ec2
    driver:
      username: ubuntu
      image_id: ami-74e27e1c
    run_list:
      - recipe[amazon-ecs-agent]
    attributes:
      amazon-ecs-agent:
        aws_access_key_id: "#{Chef::Config['aws_access_key_id']}"
        aws_secret_access_key: "#{Chef::Config['aws_secret_access_key']}"