---
driver:
  name: vagrant


provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-16.04

suites:
  - name: default
    run_list:
      - recipe[amazon-ecs-agent]
    attributes:

  - name: default-ec2
    driver_plugin: ec2
    driver:
      username: ubuntu
      image_id: ami-74e27e1c
    run_list:
      - recipe[amazon-ecs-agent]
    attributes:
      amazon-ecs-agent:
        aws_access_key_id: <%= ENV['AWS_ACCESS_KEY_ID'] %>
        aws_secret_access_key: <%= ENV['AWS_SECRET_ACCESS_KEY'] %>
